# Generated by Django 3.2.13 on 2022-06-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyPart', models.CharField(max_length=200)),
                ('equipment', models.CharField(max_length=120)),
                ('gifUrl', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=120)),
            ],
        ),
    ]
