# Generated by Django 3.2.13 on 2022-06-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220629_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='bodyPart',
            new_name='bodyPart2',
        ),
    ]
