# Generated by Django 3.2.13 on 2022-06-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_bodypart_exercise_bodypart2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='bodyPart2',
            new_name='bodyPart',
        ),
    ]
