# Generated by Django 3.2.13 on 2022-06-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_bodypart2_exercise_bodypart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypart',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
